# Generated by Django 4.2.7 on 2023-11-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='calculated_balance',
            field=models.FloatField(default=0.0),
        ),
    ]
